name: Move issues to In progress status when it is linked to a branch

on:
  issues:
    types:
      - linked

jobs:
  move-issue-when-linked:
    name: Move issues to In progress status when a branch/PR is linked
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project-url: https://github.com/orgs/AleLise/projects/2
          column: In Progress
          github-token: ${{ secrets.GITHUB_TOKEN }}
