name: Publish utbot-intellij and utbot-cli as an archive

on:
  push:
    branches: [main]
    
jobs:
    publish_utbot_java:
      if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
      runs-on: ubuntu-20.04
      env:
        VERSION: ${{ format('1.0.{0}', github.run_number) }}
      
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'liberica'
          java-package: jdk+fx
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.8
          
      - name: Build UTBot IntelliJ IDEA plugin
        run: |
          export KOTLIN_HOME="/usr"
          gradle buildPlugin
          cd utbot-intellij/build/distributions
          mv $(find . -type f -iname "utbot-intellij*.zip") utbot-intellij-${{ env.VERSION }}.zip
          unzip utbot-intellij-${{ env.VERSION }}.zip
          rm utbot-intellij-${{ env.VERSION }}.zip
      - name: Archive UTBot IntelliJ IDEA plugin
        uses: actions/upload-artifact@v2
        with:
          name: utbot-intellij-${{ env.VERSION }}
          path: utbot-intellij/build/distributions/*
          
      - name: Build UTBot CLI
        run: |
          export KOTLIN_HOME="/usr"
          cd utbot-cli
          gradle clean build
          cd build/libs
          mv $(find . -type f -iname "utbot-cli*.jar") utbot-cli-${{ env.VERSION }}.jar
      - name: Archive UTBot CLI
        uses: actions/upload-artifact@v2
        with:
          name: utbot-cli-${{ env.VERSION }}
          path: utbot-cli/build/libs/utbot-cli-${{ env.VERSION }}.jar