name: "Plugin and CLI: publish as archives"
on:
  push:
    branches:
      - 'main'
      - 'unit-test-bot/r**'

jobs:
    publish_plugin_and_cli:
      uses: ./.github/workflows/publish-plugin-and-cli-from-branch.yml
      with: 
        minor-release: 'none'
        upload-artifact: true
      secrets: inherit
