name: "[M] Run chosen tests"

on: 
  workflow_dispatch:
    inputs:
        project-name:
          type: choice
          description: "Project you want to run tests for."
          required: true
          default: utbot-framework
          options:
          - utbot-analytics
          - utbot-cli
          - utbot-core
          - utbot-framework-api
          - utbot-framework
          - utbot-java-fuzzing
          - utbot-gradle
          - utbot-instrumentation-tests
          - utbot-instrumentation
          - utbot-intellij-main
          - utbot-sample
          - utbot-summary
          - utbot-summary-tests
        tests-bunch-name:
          type: string
          required: true
          description: "{package-name}.{class-name-optional}.{test-name-optional}"

env:
  PUSHGATEWAY_HOSTNAME: monitoring.utbot.org

jobs:
    run-chosen-tests:
      runs-on: ubuntu-20.04
      container: unittestbot/java-env:java17-zulu-jdk-gradle7.6.1-kotlinc1.8.0

      steps:
      - name: Print environment variables
        run: printenv

      - uses: actions/checkout@v3
      
      - name: Run monitoring
        run: |
          echo Find your Prometheus metrics using label {instance=\"${GITHUB_RUN_ID}-${HOSTNAME}\"}
          chmod +x ./scripts/project/monitoring.sh
          ./scripts/project/monitoring.sh ${PUSHGATEWAY_HOSTNAME} ${{ secrets.PUSHGATEWAY_USER }} ${{ secrets.PUSHGATEWAY_PASSWORD }}
          
      - name: Run chosen tests
        run: |
          gradle :${{ github.event.inputs.project-name }}:test -PprojectType=Ultimate --no-daemon --build-cache --no-parallel -Dorg.gradle.jvmargs=-Xmx2g -Dkotlin.daemon.jvm.options=-Xmx4g --tests ${{ github.event.inputs.tests-bunch-name }}
          
      - name: Upload ${{ github.event.inputs.project-name }} tests report if tests have failed
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.project-name }}-tests-report
          path: ${{ github.event.inputs.project-name }}/build/reports/tests/test/*
          
      - name: Upload generated tests 
        if: ${{ always() && github.event.inputs.project-name == 'utbot-framework' }}
        uses: actions/upload-artifact@v3
        with:
          name: generated-tests
          path: |
            /tmp/UTBot/generated*/*
            /tmp/UTBot/utbot-instrumentedprocess-errors/*
      - name: Upload utbot-framework logs
        if: ${{ always() && github.event.inputs.project-name == 'utbot-framework' }}
        uses: actions/upload-artifact@v3
        with:
          name: utbot-framework-logs
          path: utbot-framework/logs/*
